name: "simple workflow pm2"
on: [push]
jobs:
  chech-pm2-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g pm2"
      - run: pm2 -v
